### ISSUE TITLE
Monitoring external web pages or web sites?

### ISSUE THREAD

**Issue by connecteev** [benmatselby/gollum-page-watcher-action#22]
Hi @benmatselby thanks for this github action. Can this be used to watch and minitor changes made to external web pages or sites?
Thanks!

**Comment by benmatselby** [comment]
Hey @connecteev I think that would be a different kind of action. This listens to the "gollum" event in the GitHub ecosystem and actions that.

To monitor other pages/websites, you would need to run on a cron based system I suspect.

**Comment by connecteev** [comment]
Hi @benmatselby thanks for the clarification! I see what you mean now. It would definitely be neat to leverage github actions to monitor external webpages like that. Trying to find something like that!
