### ISSUE TITLE
Show who made the change in the Slack message

### ISSUE THREAD

**Issue by markgaze** [benmatselby/gollum-page-watcher-action#7]
It would be nice to see which GitHub user made the change to the wiki page in the Slack message. Looking at https://developer.github.com/v3/activity/events/types/#gollumevent, there seems to be this information in the event data 🙂

**Comment by markgaze** [comment]
You could potentially use their name as the user in the Slack message and their image from GitHub :)

**Comment by markgaze** [comment]
Or do it similar to the way the actual GitHub integration does it:

![image](https://user-images.githubusercontent.com/16718355/76081209-8771a700-5fa0-11ea-8e66-cf23f540554c.png)

**Comment by markgaze** [comment]
:hero:

**Comment by benmatselby** [comment]
Thanks for raising @markgaze 

I looked at adding a commit message, but from what _I've seen_ so far, folks don't add a message for wiki "commits" so it doesn't seem to add too much value at the moment.

**Comment by markgaze** [comment]
No problem. Yeah, I nearly logged an issue for that too but I'm not sure if we do it enough. Might be worth doing it if there is one though, would be nice to see the thought process 🙂

**Comment by benmatselby** [comment]
Raised an issue, see above. 👍
